language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
env:
  global:
  - PINS="hello:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="hello" OCAML_VERSION="4.09"
